const SIGNUP_START = "SIGNUP_START";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAIL = "SIGNUP_FAIL";

const LOGIN_START = "LOGIN_START";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const LOGOUT_START = "LOGOUT_START";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";

const GOOGLE_START = "GOOGLE_START";
const GOOGLE_SUCCESS = "GOOGLE_SUCCESS";
const GOOGLE_FAIL = "GOOGLE_FAIL";

const SET_USER = "SET_USER";

export default {
  SIGNUP_START,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_FAIL,
  SET_USER,
  GOOGLE_START,
  GOOGLE_SUCCESS,
  GOOGLE_FAIL,
};
